
[display]
height = 1080
width = 1920
fps = 60

[paddle]
height = 200
width = 10
speed_x = 0
speed_y = 8

[player_location]
x = 1890
y = 420

[bot_location]
x = 20
y = 420

[ball]
radius = 20
speed_x = 7
speed_y = 10
x = 400
y = 200